service: videolyzer

provider:
  name: aws
  runtime: python3.7
  profile: ${file(../config.${self:provider.stage}.json):videolyzer.profile}

functions:
  startProcessingVideo:
    handler: handler.startProcessingVideo
    events:
      - s3:
          bucket:  ${file(../config.${self:provider.stage}.json):videolyzer.videos_bucket}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .mp4
